#%RAML 1.0 Trait

headers:
  clientID:
    type: string
    required: true
    example: "abc123"

  clientSecret:
    type: string
    required: true
    example: "secret123"

  Content-Type:
    type: string
    required: true
    example: "application/json"

  traceID:
    type: string
    required: true
    example: "TRC123456"